# Most settings taken from https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
# site_name: "Get Security Done"
site_name: The blueprint
site_url: https://oobecomau.github.io/theblueprint # Primary URL

site_name_oobe: oobe a Fujitsu company
site_url_oobe: https://www.oobe.com.au
site_name_o: oobe.com.au

site_url_pp: https://www.oobe.com.au/about/privacy
site_name_pp: Privacy policy

site_url_c: https://www.oobe.com.au/about/contact
site_name_c: Contact Us

site_url_ms: https://www.macrosine.com.au/
site_url_p365: https://www.perimeta.com.au/
site_url_cs: https://www.oobe.com.au/about/contact
# # Left hand Navigation menu
# nav:
#     - About this Project: 'README.md'
#     - Author(s): 'Author.md' 
#     - Assumed Knowledge: 'AssumedKnowledge.md'
#     - General Identity Tips: 'Identity.md'
#     - Original GSD project in one Page: 'GSD.md'
#     - 1. Microsoft Defender for Identity (MDI): 'MDI.md'
#     - 2. Conditional Access (CA): 'CondAccess.md'
#     - 3. Microsoft Defender for Cloud Apps (MDCA): 'MDCA.md'
#     - 4. Microsoft Defender for Endpoint (MDE): 'MDE.md'
#     - 5. Microsoft Defender for Office (MDO): 'MDO.md'
#     - 6. Microsoft Defender for Cloud (MDC): 'MDC.md'
#     - 7. Microsoft Sentinel Content: 'Sentinel.md'
#     - 8. Microsoft Information Protection (MIP/AIP): 'MIP.md'
#     - 9. ASD/ACSC Essential 8 & Hardening Guides: 'ASD.md'
#     - 10. Windows Defender App Control (WDAC): 'WDAC.md'
#     - Ninja Security Training Content: 'Ninja.md'
#     - Security Interactive Guides & Product Trials: 'Guides.md'
#     - Partner Content: 'partner.md'

# Configuration
repo_url: https://github.com/martincaddick/gsd_test
repo_name: "Get Security Done"
theme:
  name: material
  custom_dir: overrides
  icon: 
    repo: fontawesome/brands/git-alt
    admonition:
      <type>: octicons/alert-16 # material/alert
#  custom_dir: !ENV [THEME_DIR, "material"]
# Default values, taken from mkdocs_theme.yml
  features:
    # - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    #- navigation.expand
    - navigation.indexes
    # - navigation.instant
    #- navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # font:
  #  text: Roboto
  #  code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
# docs_dir: docs
# Plugins
plugins:
  - search
  - simple
  #- simple:
  #    include_extensions:
  #    - ".git/**"
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
      timezone: Australia/Sydney
  - glightbox:
      auto_caption: true
  #- social
  #- awesome-list
  #- table-reader - DON'T use, relys on pandas, too heavy for this
  #- img2fig - Not needed
  - mermaid2
  #- macros
  #- minify 

# Customization
extra:
  consent:
    actions:
      - accept
      - manage
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  # analytics:
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/thumb-up-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/thumb-down-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >- 
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  #   provider: google
  #   property: G-QS5J5W9G3Q
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/martincaddick/
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/dcaddick
    # - icon: fontawesome/brands/linkedin
    #   link: https://linkedin.com/in/dcaddick/

# Markdown Extensions 
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list
  - meta
  - md_in_html
  - admonition
  - footnotes
#   - pymdownx.critic
#   - pymdownx.caret
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.tilde
#   - pymdownx.details
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg
