site_name: "Demo GSD Site"
plugins:
- simple
- search
- awesome-pages
- macros
- social
# (optional) The URL of the repository the docs should point to
repo_url: https://github.com/martincaddick/gsd_test 
# (optional) The URL of the site
site_url: https://martincaddick.github.io
# (optional) The edit URI
edit_uri: edit/main/
site_description: Getting Security Done
site_author: David Caddick
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dcaddick
theme:
  name: material

    
