# Most settings taken from https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
site_name: "The blueprint for Review"


# Configuration
repo_url: https://github.com/martincaddick/gsd_test
repo_name: "The blueprint for Review"

theme:
  name: material
  icon: 
    repo: fontawesome/brands/git-alt
    admonition:
      <type>: octicons/alert-16 # material/alert
  # custom_dir: overrides
# Default values, taken from mkdocs_theme.yml
  features:
    # - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    #- navigation.expand
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # font:
  #  text: Roboto
  #  code: Roboto Mono
  # favicon: assets/favicon.png
#   icon:
#     logo: logo
docs_dir: docs
# Plugins
plugins:
  - search
  - simple
  - awesome-pages
  # - mike:
  #   canonical_version: latest
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
      timezone: Australia/Sydney
  # - glightbox:
  #     auto_caption: true
  #- social
  # - awesome-list
  #- table-reader - DON'T use, relys on pandas, too heavy for this
  #- img2fig - Not needed
  # - mermaid2
  #- macros
  #- minify 

# Customization
extra:
  version:
    provider: mike

# Markdown Extensions 
markdown_extensions:
  - attr_list
  - meta
  - md_in_html
  # removed for testing
  # - admonition
  # - footnotes
  # - pymdownx.critic
  # - pymdownx.caret
  # - pymdownx.keys
  # - pymdownx.mark
  # - pymdownx.tilde
  # - pymdownx.details
  # - pymdownx.highlight:
  #     anchor_linenums: true
  # - pymdownx.inlinehilite
  # - pymdownx.snippets
  # - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  # - mkdocs-click
