name: Bard
on:
  pull_request:
    types: [opened,synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install mkdocs-material

        #   Build Documentation
      - name: Build documentation
        run: mkdocs build

      - name: Compare Changes
        id: compare_changes
        uses: actions/upload-artifact@v3
        with:
          name: generated-docs
          path: site
        
        # Update engine branch
      - name: Update engine branch if changes detected
        run: |
          ls -l site/*
          git checkout engine
          git merge blueprint
          git add site/*
          git commit -m "Update engine documentation to include blueprint changes"
          git push origin engine

        #   Notify reviwer
      - name: Notify reviewer
        if: steps.compare_changes.outputs.artifact_size > 0
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.create({
                title: "Documentation update available for review",
                body: "The documentation has been updated and is ready for review. Please review the changes on the dev branch.",
                assignees: ["martincaddick"]
            })


