name: Create Branch on Pull Release
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create new branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b new-branch
          git push origin new-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
