# This is a basic workflow to help you get started with Actions

name: MakeDocs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docs
        uses: athackst/mkdocs-simple-plugin@v2.1.3
        with:
        #   # (optional) Specify branch 
        #   publish_branch: main # gh-pages 
          # (optional) The URL of the repository the docs should point to
          repo_url: https://github.com/martincaddick/gsd_test 
        #   # (optional) The name of the site
          site_name: gsd_test
          plugins:
            - simple
          # (optional) The URL of the site
          site_url: https://martincaddick.github.io
          # (optional) The edit URI
          edit_uri: edit/main/
        #   # (optional) Specify a google analytics key 
        #   # google_analytics: UA-XXXXXXX
        #   # (optional) Specify a different theme [mkdocs|readthedocs|material]
          theme: material
        #   # (optional) Load a configuration file from a string
        #   # config: "mkdocs.yml"
        #   # (optional) Version or alias.  Specify multiple aliases with space
        #   # example: version: v0.1.0 latest
        #   version: latest
        #   # (optional) The version that will be served by the root of your site
        #   default_version: latest
        #   # (optional) Whether to push the docs to the remote branch
        #   # push: 1
